# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monthlyprojects_makebooking.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_makebooking_diag(object):
    def setupUi(self, makebooking_diag):
        makebooking_diag.setObjectName(_fromUtf8("makebooking_diag"))
        makebooking_diag.resize(787, 415)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(makebooking_diag.sizePolicy().hasHeightForWidth())
        makebooking_diag.setSizePolicy(sizePolicy)
        makebooking_diag.setWindowOpacity(1.0)
        makebooking_diag.setAutoFillBackground(False)
        self.gridLayout_2 = QtGui.QGridLayout(makebooking_diag)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bookingTypeTab = QtGui.QTabWidget(makebooking_diag)
        self.bookingTypeTab.setTabShape(QtGui.QTabWidget.Triangular)
        self.bookingTypeTab.setUsesScrollButtons(False)
        self.bookingTypeTab.setDocumentMode(False)
        self.bookingTypeTab.setObjectName(_fromUtf8("bookingTypeTab"))
        self.singleInstanceBooking = QtGui.QWidget()
        self.singleInstanceBooking.setObjectName(_fromUtf8("singleInstanceBooking"))
        self.gridLayout_8 = QtGui.QGridLayout(self.singleInstanceBooking)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(90, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.otb_equipment = QtGui.QComboBox(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_equipment.sizePolicy().hasHeightForWidth())
        self.otb_equipment.setSizePolicy(sizePolicy)
        self.otb_equipment.setMinimumSize(QtCore.QSize(158, 20))
        self.otb_equipment.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_equipment.setObjectName(_fromUtf8("otb_equipment"))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.otb_equipment.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.otb_equipment)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.otb_setup = QtGui.QCheckBox(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_setup.sizePolicy().hasHeightForWidth())
        self.otb_setup.setSizePolicy(sizePolicy)
        self.otb_setup.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_setup.setObjectName(_fromUtf8("otb_setup"))
        self.horizontalLayout_4.addWidget(self.otb_setup)
        self.otb_pickup = QtGui.QCheckBox(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_pickup.sizePolicy().hasHeightForWidth())
        self.otb_pickup.setSizePolicy(sizePolicy)
        self.otb_pickup.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_pickup.setObjectName(_fromUtf8("otb_pickup"))
        self.horizontalLayout_4.addWidget(self.otb_pickup)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 4, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_14.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_8 = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_14.addWidget(self.label_8)
        self.otb_notes = QtGui.QTextEdit(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_notes.sizePolicy().hasHeightForWidth())
        self.otb_notes.setSizePolicy(sizePolicy)
        self.otb_notes.setMinimumSize(QtCore.QSize(80, 80))
        self.otb_notes.setBaseSize(QtCore.QSize(60, 40))
        self.otb_notes.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_notes.setObjectName(_fromUtf8("otb_notes"))
        self.horizontalLayout_14.addWidget(self.otb_notes)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 6, 0, 1, 1)
        self.otb_buttonBox = QtGui.QDialogButtonBox(self.singleInstanceBooking)
        self.otb_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.otb_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.otb_buttonBox.setCenterButtons(True)
        self.otb_buttonBox.setObjectName(_fromUtf8("otb_buttonBox"))
        self.gridLayout_8.addWidget(self.otb_buttonBox, 7, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.otb_techAssignedInput = QtGui.QLineEdit(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_techAssignedInput.sizePolicy().hasHeightForWidth())
        self.otb_techAssignedInput.setSizePolicy(sizePolicy)
        self.otb_techAssignedInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_techAssignedInput.setObjectName(_fromUtf8("otb_techAssignedInput"))
        self.horizontalLayout_3.addWidget(self.otb_techAssignedInput)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_49 = QtGui.QLabel(self.singleInstanceBooking)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_11.addWidget(self.label_49)
        self.otb_setupLocationInput = QtGui.QLineEdit(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_setupLocationInput.sizePolicy().hasHeightForWidth())
        self.otb_setupLocationInput.setSizePolicy(sizePolicy)
        self.otb_setupLocationInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_setupLocationInput.setObjectName(_fromUtf8("otb_setupLocationInput"))
        self.horizontalLayout_11.addWidget(self.otb_setupLocationInput)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.gridLayout_8.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label_7 = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.otb_timeOut = QtGui.QTimeEdit(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_timeOut.sizePolicy().hasHeightForWidth())
        self.otb_timeOut.setSizePolicy(sizePolicy)
        self.otb_timeOut.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_timeOut.setObjectName(_fromUtf8("otb_timeOut"))
        self.horizontalLayout_8.addWidget(self.otb_timeOut)
        self.label_6 = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.otb_timeIn = QtGui.QTimeEdit(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_timeIn.sizePolicy().hasHeightForWidth())
        self.otb_timeIn.setSizePolicy(sizePolicy)
        self.otb_timeIn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_timeIn.setObjectName(_fromUtf8("otb_timeIn"))
        self.horizontalLayout_8.addWidget(self.otb_timeIn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.otb_dateStart = QtGui.QDateEdit(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_dateStart.sizePolicy().hasHeightForWidth())
        self.otb_dateStart.setSizePolicy(sizePolicy)
        self.otb_dateStart.setMinimumSize(QtCore.QSize(50, 20))
        self.otb_dateStart.setBaseSize(QtCore.QSize(50, 20))
        self.otb_dateStart.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_dateStart.setFrame(True)
        self.otb_dateStart.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.otb_dateStart.setAccelerated(False)
        self.otb_dateStart.setCalendarPopup(True)
        self.otb_dateStart.setObjectName(_fromUtf8("otb_dateStart"))
        self.horizontalLayout_9.addWidget(self.otb_dateStart)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.otb_sameDay = QtGui.QCheckBox(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_sameDay.sizePolicy().hasHeightForWidth())
        self.otb_sameDay.setSizePolicy(sizePolicy)
        self.otb_sameDay.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_sameDay.setChecked(True)
        self.otb_sameDay.setObjectName(_fromUtf8("otb_sameDay"))
        self.horizontalLayout_10.addWidget(self.otb_sameDay)
        self.otb_notSameDay = QtGui.QFrame(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_notSameDay.sizePolicy().hasHeightForWidth())
        self.otb_notSameDay.setSizePolicy(sizePolicy)
        self.otb_notSameDay.setMinimumSize(QtCore.QSize(150, 15))
        self.otb_notSameDay.setFrameShape(QtGui.QFrame.NoFrame)
        self.otb_notSameDay.setFrameShadow(QtGui.QFrame.Plain)
        self.otb_notSameDay.setObjectName(_fromUtf8("otb_notSameDay"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.otb_notSameDay)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_10 = QtGui.QLabel(self.otb_notSameDay)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_16.addWidget(self.label_10)
        self.otb_dateEnd = QtGui.QDateEdit(self.otb_notSameDay)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_dateEnd.sizePolicy().hasHeightForWidth())
        self.otb_dateEnd.setSizePolicy(sizePolicy)
        self.otb_dateEnd.setMinimumSize(QtCore.QSize(0, 20))
        self.otb_dateEnd.setBaseSize(QtCore.QSize(50, 20))
        self.otb_dateEnd.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_dateEnd.setWrapping(False)
        self.otb_dateEnd.setFrame(True)
        self.otb_dateEnd.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.otb_dateEnd.setCalendarPopup(True)
        self.otb_dateEnd.setObjectName(_fromUtf8("otb_dateEnd"))
        self.horizontalLayout_16.addWidget(self.otb_dateEnd)
        self.horizontalLayout_10.addWidget(self.otb_notSameDay)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.otb_ticketNumInput = QtGui.QLineEdit(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_ticketNumInput.sizePolicy().hasHeightForWidth())
        self.otb_ticketNumInput.setSizePolicy(sizePolicy)
        self.otb_ticketNumInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_ticketNumInput.setObjectName(_fromUtf8("otb_ticketNumInput"))
        self.horizontalLayout.addWidget(self.otb_ticketNumInput)
        self.horizontalLayout_12.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.otb_clientNameInput = QtGui.QLineEdit(self.singleInstanceBooking)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otb_clientNameInput.sizePolicy().hasHeightForWidth())
        self.otb_clientNameInput.setSizePolicy(sizePolicy)
        self.otb_clientNameInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.otb_clientNameInput.setObjectName(_fromUtf8("otb_clientNameInput"))
        self.horizontalLayout_2.addWidget(self.otb_clientNameInput)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.bookingTypeTab.addTab(self.singleInstanceBooking, _fromUtf8(""))
        self.weeklyInstanceBookings = QtGui.QWidget()
        self.weeklyInstanceBookings.setObjectName(_fromUtf8("weeklyInstanceBookings"))
        self.gridLayout = QtGui.QGridLayout(self.weeklyInstanceBookings)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_25 = QtGui.QLabel(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_17.addWidget(self.label_25)
        self.wb_ticketNumInput = QtGui.QLineEdit(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_ticketNumInput.sizePolicy().hasHeightForWidth())
        self.wb_ticketNumInput.setSizePolicy(sizePolicy)
        self.wb_ticketNumInput.setObjectName(_fromUtf8("wb_ticketNumInput"))
        self.horizontalLayout_17.addWidget(self.wb_ticketNumInput)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_24 = QtGui.QLabel(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_19.addWidget(self.label_24)
        self.wb_clientNameInput = QtGui.QLineEdit(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_clientNameInput.sizePolicy().hasHeightForWidth())
        self.wb_clientNameInput.setSizePolicy(sizePolicy)
        self.wb_clientNameInput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.wb_clientNameInput.setObjectName(_fromUtf8("wb_clientNameInput"))
        self.horizontalLayout_19.addWidget(self.wb_clientNameInput)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_19)
        self.gridLayout.addLayout(self.horizontalLayout_36, 0, 0, 1, 2)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_36 = QtGui.QLabel(self.weeklyInstanceBookings)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_18.addWidget(self.label_36)
        self.wb_techAssignedInput = QtGui.QLineEdit(self.weeklyInstanceBookings)
        self.wb_techAssignedInput.setObjectName(_fromUtf8("wb_techAssignedInput"))
        self.horizontalLayout_18.addWidget(self.wb_techAssignedInput)
        self.gridLayout.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_52 = QtGui.QLabel(self.weeklyInstanceBookings)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_20.addWidget(self.label_52)
        self.wb_setupLocationInput = QtGui.QLineEdit(self.weeklyInstanceBookings)
        self.wb_setupLocationInput.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_setupLocationInput.sizePolicy().hasHeightForWidth())
        self.wb_setupLocationInput.setSizePolicy(sizePolicy)
        self.wb_setupLocationInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.wb_setupLocationInput.setObjectName(_fromUtf8("wb_setupLocationInput"))
        self.horizontalLayout_20.addWidget(self.wb_setupLocationInput)
        self.gridLayout.addLayout(self.horizontalLayout_20, 1, 2, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_68 = QtGui.QLabel(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_21.addWidget(self.label_68)
        self.wb_equipment = QtGui.QComboBox(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_equipment.sizePolicy().hasHeightForWidth())
        self.wb_equipment.setSizePolicy(sizePolicy)
        self.wb_equipment.setObjectName(_fromUtf8("wb_equipment"))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.wb_equipment.addItem(_fromUtf8(""))
        self.horizontalLayout_21.addWidget(self.wb_equipment)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_21, 2, 0, 1, 2)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_69 = QtGui.QLabel(self.weeklyInstanceBookings)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_23.addWidget(self.label_69)
        self.wb_setup = QtGui.QCheckBox(self.weeklyInstanceBookings)
        self.wb_setup.setObjectName(_fromUtf8("wb_setup"))
        self.horizontalLayout_23.addWidget(self.wb_setup)
        self.wb_pickup = QtGui.QCheckBox(self.weeklyInstanceBookings)
        self.wb_pickup.setObjectName(_fromUtf8("wb_pickup"))
        self.horizontalLayout_23.addWidget(self.wb_pickup)
        self.gridLayout.addLayout(self.horizontalLayout_23, 2, 2, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.label_37 = QtGui.QLabel(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_22.addWidget(self.label_37)
        self.wb_dateStart = QtGui.QDateEdit(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_dateStart.sizePolicy().hasHeightForWidth())
        self.wb_dateStart.setSizePolicy(sizePolicy)
        self.wb_dateStart.setCalendarPopup(True)
        self.wb_dateStart.setObjectName(_fromUtf8("wb_dateStart"))
        self.horizontalLayout_22.addWidget(self.wb_dateStart)
        self.label_38 = QtGui.QLabel(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_22.addWidget(self.label_38)
        self.wb_dateEnd = QtGui.QDateEdit(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_dateEnd.sizePolicy().hasHeightForWidth())
        self.wb_dateEnd.setSizePolicy(sizePolicy)
        self.wb_dateEnd.setCalendarPopup(True)
        self.wb_dateEnd.setObjectName(_fromUtf8("wb_dateEnd"))
        self.horizontalLayout_22.addWidget(self.wb_dateEnd)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_22, 3, 0, 1, 2)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.groupBox_6 = QtGui.QGroupBox(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.wb_monday = QtGui.QCheckBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_monday.sizePolicy().hasHeightForWidth())
        self.wb_monday.setSizePolicy(sizePolicy)
        self.wb_monday.setObjectName(_fromUtf8("wb_monday"))
        self.gridLayout_3.addWidget(self.wb_monday, 0, 0, 1, 2)
        self.label_39 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 1, 0, 1, 1)
        self.wb_timeOutMonday = QtGui.QTimeEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeOutMonday.sizePolicy().hasHeightForWidth())
        self.wb_timeOutMonday.setSizePolicy(sizePolicy)
        self.wb_timeOutMonday.setObjectName(_fromUtf8("wb_timeOutMonday"))
        self.gridLayout_3.addWidget(self.wb_timeOutMonday, 1, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_3.addWidget(self.label_40, 2, 0, 1, 1)
        self.wb_timeInMonday = QtGui.QTimeEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeInMonday.sizePolicy().hasHeightForWidth())
        self.wb_timeInMonday.setSizePolicy(sizePolicy)
        self.wb_timeInMonday.setObjectName(_fromUtf8("wb_timeInMonday"))
        self.gridLayout_3.addWidget(self.wb_timeInMonday, 2, 1, 1, 1)
        self.horizontalLayout_24.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_42 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_4.addWidget(self.label_42, 2, 0, 1, 1)
        self.wb_timeInTuesday = QtGui.QTimeEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeInTuesday.sizePolicy().hasHeightForWidth())
        self.wb_timeInTuesday.setSizePolicy(sizePolicy)
        self.wb_timeInTuesday.setObjectName(_fromUtf8("wb_timeInTuesday"))
        self.gridLayout_4.addWidget(self.wb_timeInTuesday, 2, 1, 1, 1)
        self.wb_timeOutTuesday = QtGui.QTimeEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeOutTuesday.sizePolicy().hasHeightForWidth())
        self.wb_timeOutTuesday.setSizePolicy(sizePolicy)
        self.wb_timeOutTuesday.setObjectName(_fromUtf8("wb_timeOutTuesday"))
        self.gridLayout_4.addWidget(self.wb_timeOutTuesday, 1, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_4.addWidget(self.label_41, 1, 0, 1, 1)
        self.wb_tuesday = QtGui.QCheckBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_tuesday.sizePolicy().hasHeightForWidth())
        self.wb_tuesday.setSizePolicy(sizePolicy)
        self.wb_tuesday.setObjectName(_fromUtf8("wb_tuesday"))
        self.gridLayout_4.addWidget(self.wb_tuesday, 0, 0, 1, 2)
        self.horizontalLayout_24.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.wb_timeOutWednesday = QtGui.QTimeEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeOutWednesday.sizePolicy().hasHeightForWidth())
        self.wb_timeOutWednesday.setSizePolicy(sizePolicy)
        self.wb_timeOutWednesday.setObjectName(_fromUtf8("wb_timeOutWednesday"))
        self.gridLayout_5.addWidget(self.wb_timeOutWednesday, 1, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_5.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_5.addWidget(self.label_44, 2, 0, 1, 1)
        self.wb_timeInWednesday = QtGui.QTimeEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeInWednesday.sizePolicy().hasHeightForWidth())
        self.wb_timeInWednesday.setSizePolicy(sizePolicy)
        self.wb_timeInWednesday.setObjectName(_fromUtf8("wb_timeInWednesday"))
        self.gridLayout_5.addWidget(self.wb_timeInWednesday, 2, 1, 1, 1)
        self.wb_wednesday = QtGui.QCheckBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_wednesday.sizePolicy().hasHeightForWidth())
        self.wb_wednesday.setSizePolicy(sizePolicy)
        self.wb_wednesday.setObjectName(_fromUtf8("wb_wednesday"))
        self.gridLayout_5.addWidget(self.wb_wednesday, 0, 0, 1, 2)
        self.horizontalLayout_24.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.wb_thursday = QtGui.QCheckBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_thursday.sizePolicy().hasHeightForWidth())
        self.wb_thursday.setSizePolicy(sizePolicy)
        self.wb_thursday.setObjectName(_fromUtf8("wb_thursday"))
        self.gridLayout_6.addWidget(self.wb_thursday, 0, 0, 1, 2)
        self.label_45 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_6.addWidget(self.label_45, 1, 0, 1, 1)
        self.wb_timeOutThursday = QtGui.QTimeEdit(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeOutThursday.sizePolicy().hasHeightForWidth())
        self.wb_timeOutThursday.setSizePolicy(sizePolicy)
        self.wb_timeOutThursday.setObjectName(_fromUtf8("wb_timeOutThursday"))
        self.gridLayout_6.addWidget(self.wb_timeOutThursday, 1, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_6.addWidget(self.label_46, 2, 0, 1, 1)
        self.wb_timeInThursday = QtGui.QTimeEdit(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeInThursday.sizePolicy().hasHeightForWidth())
        self.wb_timeInThursday.setSizePolicy(sizePolicy)
        self.wb_timeInThursday.setObjectName(_fromUtf8("wb_timeInThursday"))
        self.gridLayout_6.addWidget(self.wb_timeInThursday, 2, 1, 1, 1)
        self.horizontalLayout_24.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setTitle(_fromUtf8(""))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.wb_friday = QtGui.QCheckBox(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_friday.sizePolicy().hasHeightForWidth())
        self.wb_friday.setSizePolicy(sizePolicy)
        self.wb_friday.setObjectName(_fromUtf8("wb_friday"))
        self.gridLayout_7.addWidget(self.wb_friday, 0, 0, 1, 2)
        self.label_47 = QtGui.QLabel(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_7.addWidget(self.label_47, 1, 0, 1, 1)
        self.wb_timeOutFriday = QtGui.QTimeEdit(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeOutFriday.sizePolicy().hasHeightForWidth())
        self.wb_timeOutFriday.setSizePolicy(sizePolicy)
        self.wb_timeOutFriday.setObjectName(_fromUtf8("wb_timeOutFriday"))
        self.gridLayout_7.addWidget(self.wb_timeOutFriday, 1, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_7.addWidget(self.label_48, 2, 0, 1, 1)
        self.wb_timeInFriday = QtGui.QTimeEdit(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_timeInFriday.sizePolicy().hasHeightForWidth())
        self.wb_timeInFriday.setSizePolicy(sizePolicy)
        self.wb_timeInFriday.setObjectName(_fromUtf8("wb_timeInFriday"))
        self.gridLayout_7.addWidget(self.wb_timeInFriday, 2, 1, 1, 1)
        self.horizontalLayout_24.addWidget(self.groupBox_10)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_24, 4, 0, 1, 3)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_57 = QtGui.QLabel(self.weeklyInstanceBookings)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.verticalLayout_7.addWidget(self.label_57)
        self.wb_notes = QtGui.QTextEdit(self.weeklyInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wb_notes.sizePolicy().hasHeightForWidth())
        self.wb_notes.setSizePolicy(sizePolicy)
        self.wb_notes.setFocusPolicy(QtCore.Qt.TabFocus)
        self.wb_notes.setObjectName(_fromUtf8("wb_notes"))
        self.verticalLayout_7.addWidget(self.wb_notes)
        self.gridLayout.addLayout(self.verticalLayout_7, 5, 0, 1, 3)
        self.wb_buttonBox = QtGui.QDialogButtonBox(self.weeklyInstanceBookings)
        self.wb_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.wb_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.wb_buttonBox.setCenterButtons(True)
        self.wb_buttonBox.setObjectName(_fromUtf8("wb_buttonBox"))
        self.gridLayout.addWidget(self.wb_buttonBox, 6, 0, 1, 3)
        self.bookingTypeTab.addTab(self.weeklyInstanceBookings, _fromUtf8(""))
        self.multipleInstanceBookings = QtGui.QWidget()
        self.multipleInstanceBookings.setObjectName(_fromUtf8("multipleInstanceBookings"))
        self.gridLayout_9 = QtGui.QGridLayout(self.multipleInstanceBookings)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_63 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.horizontalLayout_26.addWidget(self.label_63)
        self.mib_ticketNumInput = QtGui.QLineEdit(self.multipleInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mib_ticketNumInput.sizePolicy().hasHeightForWidth())
        self.mib_ticketNumInput.setSizePolicy(sizePolicy)
        self.mib_ticketNumInput.setMinimumSize(QtCore.QSize(30, 20))
        self.mib_ticketNumInput.setBaseSize(QtCore.QSize(40, 20))
        self.mib_ticketNumInput.setObjectName(_fromUtf8("mib_ticketNumInput"))
        self.horizontalLayout_26.addWidget(self.mib_ticketNumInput)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_62 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.horizontalLayout_27.addWidget(self.label_62)
        self.mib_clientNameInput = QtGui.QLineEdit(self.multipleInstanceBookings)
        self.mib_clientNameInput.setObjectName(_fromUtf8("mib_clientNameInput"))
        self.horizontalLayout_27.addWidget(self.mib_clientNameInput)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_27)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_65 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.horizontalLayout_25.addWidget(self.label_65)
        self.mib_techAssignedInput = QtGui.QLineEdit(self.multipleInstanceBookings)
        self.mib_techAssignedInput.setObjectName(_fromUtf8("mib_techAssignedInput"))
        self.horizontalLayout_25.addWidget(self.mib_techAssignedInput)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_51 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_15.addWidget(self.label_51)
        self.mib_setupLocationInput = QtGui.QLineEdit(self.multipleInstanceBookings)
        self.mib_setupLocationInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.mib_setupLocationInput.setObjectName(_fromUtf8("mib_setupLocationInput"))
        self.horizontalLayout_15.addWidget(self.mib_setupLocationInput)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.gridLayout_9.addLayout(self.verticalLayout, 0, 0, 1, 3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_105 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.horizontalLayout_35.addWidget(self.label_105)
        self.mib_equipment = QtGui.QComboBox(self.multipleInstanceBookings)
        self.mib_equipment.setObjectName(_fromUtf8("mib_equipment"))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.mib_equipment.addItem(_fromUtf8(""))
        self.horizontalLayout_35.addWidget(self.mib_equipment)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_102 = QtGui.QLabel(self.multipleInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_102.sizePolicy().hasHeightForWidth())
        self.label_102.setSizePolicy(sizePolicy)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.horizontalLayout_33.addWidget(self.label_102)
        self.mib_timeOut = QtGui.QTimeEdit(self.multipleInstanceBookings)
        self.mib_timeOut.setObjectName(_fromUtf8("mib_timeOut"))
        self.horizontalLayout_33.addWidget(self.mib_timeOut)
        self.gridLayout_12.addLayout(self.horizontalLayout_33, 1, 0, 1, 1)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_101 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.horizontalLayout_34.addWidget(self.label_101)
        self.mib_timeIn = QtGui.QTimeEdit(self.multipleInstanceBookings)
        self.mib_timeIn.setObjectName(_fromUtf8("mib_timeIn"))
        self.horizontalLayout_34.addWidget(self.mib_timeIn)
        self.gridLayout_12.addLayout(self.horizontalLayout_34, 1, 1, 1, 1)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_66 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_31.addWidget(self.label_66)
        self.mib_dateStart = QtGui.QDateEdit(self.multipleInstanceBookings)
        self.mib_dateStart.setCalendarPopup(True)
        self.mib_dateStart.setObjectName(_fromUtf8("mib_dateStart"))
        self.horizontalLayout_31.addWidget(self.mib_dateStart)
        self.gridLayout_12.addLayout(self.horizontalLayout_31, 0, 0, 1, 1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_67 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_32.addWidget(self.label_67)
        self.mib_dateEnd = QtGui.QDateEdit(self.multipleInstanceBookings)
        self.mib_dateEnd.setCalendarPopup(True)
        self.mib_dateEnd.setObjectName(_fromUtf8("mib_dateEnd"))
        self.horizontalLayout_32.addWidget(self.mib_dateEnd)
        self.gridLayout_12.addLayout(self.horizontalLayout_32, 0, 1, 1, 1)
        self.gridLayout_12.setRowStretch(0, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_12)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 1, 0, 2, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_64 = QtGui.QLabel(self.multipleInstanceBookings)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_11.addWidget(self.label_64, 0, 1, 1, 1)
        self.mib_setup = QtGui.QCheckBox(self.multipleInstanceBookings)
        self.mib_setup.setObjectName(_fromUtf8("mib_setup"))
        self.gridLayout_11.addWidget(self.mib_setup, 0, 2, 1, 1)
        self.mib_pickup = QtGui.QCheckBox(self.multipleInstanceBookings)
        self.mib_pickup.setObjectName(_fromUtf8("mib_pickup"))
        self.gridLayout_11.addWidget(self.mib_pickup, 0, 3, 1, 1)
        self.mib_councilRoomSetup = QtGui.QCheckBox(self.multipleInstanceBookings)
        self.mib_councilRoomSetup.setObjectName(_fromUtf8("mib_councilRoomSetup"))
        self.gridLayout_11.addWidget(self.mib_councilRoomSetup, 1, 2, 1, 1)
        self.mib_councilRoomStay = QtGui.QCheckBox(self.multipleInstanceBookings)
        self.mib_councilRoomStay.setObjectName(_fromUtf8("mib_councilRoomStay"))
        self.gridLayout_11.addWidget(self.mib_councilRoomStay, 1, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem8, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_11, 1, 1, 1, 2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.mib_addNewDate = QtGui.QPushButton(self.multipleInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mib_addNewDate.sizePolicy().hasHeightForWidth())
        self.mib_addNewDate.setSizePolicy(sizePolicy)
        self.mib_addNewDate.setObjectName(_fromUtf8("mib_addNewDate"))
        self.horizontalLayout_6.addWidget(self.mib_addNewDate)
        self.mib_removeNewDate = QtGui.QPushButton(self.multipleInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mib_removeNewDate.sizePolicy().hasHeightForWidth())
        self.mib_removeNewDate.setSizePolicy(sizePolicy)
        self.mib_removeNewDate.setObjectName(_fromUtf8("mib_removeNewDate"))
        self.horizontalLayout_6.addWidget(self.mib_removeNewDate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.mib_listView = QtGui.QListWidget(self.multipleInstanceBookings)
        self.mib_listView.setObjectName(_fromUtf8("mib_listView"))
        self.verticalLayout_2.addWidget(self.mib_listView)
        self.gridLayout_9.addLayout(self.verticalLayout_2, 2, 2, 2, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_56 = QtGui.QLabel(self.multipleInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.verticalLayout_6.addWidget(self.label_56)
        self.mib_notes = QtGui.QTextEdit(self.multipleInstanceBookings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mib_notes.sizePolicy().hasHeightForWidth())
        self.mib_notes.setSizePolicy(sizePolicy)
        self.mib_notes.setFocusPolicy(QtCore.Qt.TabFocus)
        self.mib_notes.setObjectName(_fromUtf8("mib_notes"))
        self.verticalLayout_6.addWidget(self.mib_notes)
        self.gridLayout_9.addLayout(self.verticalLayout_6, 3, 0, 1, 2)
        self.mib_buttonBox = QtGui.QDialogButtonBox(self.multipleInstanceBookings)
        self.mib_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.mib_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.mib_buttonBox.setCenterButtons(True)
        self.mib_buttonBox.setObjectName(_fromUtf8("mib_buttonBox"))
        self.gridLayout_9.addWidget(self.mib_buttonBox, 4, 0, 1, 3)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 2, 1, 1, 1)
        self.bookingTypeTab.addTab(self.multipleInstanceBookings, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.bookingTypeTab, 0, 0, 1, 1)

        self.retranslateUi(makebooking_diag)
        self.bookingTypeTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.mib_buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), makebooking_diag.accept)
        QtCore.QObject.connect(self.otb_buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), makebooking_diag.reject)
        QtCore.QObject.connect(self.otb_sameDay, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.otb_notSameDay.setHidden)
        QtCore.QObject.connect(self.otb_buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), makebooking_diag.accept)
        QtCore.QObject.connect(self.mib_buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), makebooking_diag.reject)
        QtCore.QObject.connect(self.wb_buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), makebooking_diag.accept)
        QtCore.QObject.connect(self.wb_buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), makebooking_diag.reject)
        QtCore.QMetaObject.connectSlotsByName(makebooking_diag)
        makebooking_diag.setTabOrder(self.otb_ticketNumInput, self.otb_clientNameInput)
        makebooking_diag.setTabOrder(self.otb_clientNameInput, self.otb_techAssignedInput)
        makebooking_diag.setTabOrder(self.otb_techAssignedInput, self.otb_setupLocationInput)
        makebooking_diag.setTabOrder(self.otb_setupLocationInput, self.otb_dateStart)
        makebooking_diag.setTabOrder(self.otb_dateStart, self.otb_sameDay)
        makebooking_diag.setTabOrder(self.otb_sameDay, self.otb_timeOut)
        makebooking_diag.setTabOrder(self.otb_timeOut, self.otb_timeIn)
        makebooking_diag.setTabOrder(self.otb_timeIn, self.otb_setup)
        makebooking_diag.setTabOrder(self.otb_setup, self.otb_pickup)
        makebooking_diag.setTabOrder(self.otb_pickup, self.otb_notes)
        makebooking_diag.setTabOrder(self.otb_notes, self.otb_buttonBox)
        makebooking_diag.setTabOrder(self.otb_buttonBox, self.mib_clientNameInput)
        makebooking_diag.setTabOrder(self.mib_clientNameInput, self.mib_techAssignedInput)
        makebooking_diag.setTabOrder(self.mib_techAssignedInput, self.mib_setupLocationInput)
        makebooking_diag.setTabOrder(self.mib_setupLocationInput, self.mib_setup)
        makebooking_diag.setTabOrder(self.mib_setup, self.mib_pickup)
        makebooking_diag.setTabOrder(self.mib_pickup, self.mib_councilRoomSetup)
        makebooking_diag.setTabOrder(self.mib_councilRoomSetup, self.mib_councilRoomStay)
        makebooking_diag.setTabOrder(self.mib_councilRoomStay, self.mib_dateStart)
        makebooking_diag.setTabOrder(self.mib_dateStart, self.mib_dateEnd)
        makebooking_diag.setTabOrder(self.mib_dateEnd, self.mib_timeOut)
        makebooking_diag.setTabOrder(self.mib_timeOut, self.mib_timeIn)
        makebooking_diag.setTabOrder(self.mib_timeIn, self.mib_buttonBox)

    def retranslateUi(self, makebooking_diag):
        makebooking_diag.setWindowTitle(_translate("makebooking_diag", "Monthly Projects: New Booking", None))
        self.label_5.setText(_translate("makebooking_diag", "Equipment Needed", None))
        self.otb_equipment.setItemText(0, _translate("makebooking_diag", "Laptop", None))
        self.otb_equipment.setItemText(1, _translate("makebooking_diag", "Projector", None))
        self.otb_equipment.setItemText(2, _translate("makebooking_diag", "Screen", None))
        self.otb_equipment.setItemText(3, _translate("makebooking_diag", "Speaker", None))
        self.otb_equipment.setItemText(4, _translate("makebooking_diag", "Microphone(PC)", None))
        self.otb_equipment.setItemText(5, _translate("makebooking_diag", "VGA Cable ", None))
        self.otb_equipment.setItemText(6, _translate("makebooking_diag", "Extension/Surge", None))
        self.otb_equipment.setItemText(7, _translate("makebooking_diag", "DVD Player", None))
        self.otb_equipment.setItemText(8, _translate("makebooking_diag", "VCR", None))
        self.otb_equipment.setItemText(9, _translate("makebooking_diag", "21\' Monitor", None))
        self.otb_equipment.setItemText(10, _translate("makebooking_diag", "PA System", None))
        self.otb_equipment.setItemText(11, _translate("makebooking_diag", "Video Recording", None))
        self.otb_equipment.setItemText(12, _translate("makebooking_diag", "Doc Cam", None))
        self.otb_equipment.setItemText(13, _translate("makebooking_diag", "Microphone (AV)", None))
        self.otb_equipment.setItemText(14, _translate("makebooking_diag", "Plasma Screens", None))
        self.otb_equipment.setItemText(15, _translate("makebooking_diag", "New Item", None))
        self.label_9.setText(_translate("makebooking_diag", "Setup Type", None))
        self.otb_setup.setText(_translate("makebooking_diag", "Setup ", None))
        self.otb_pickup.setText(_translate("makebooking_diag", "Pickup", None))
        self.label_8.setText(_translate("makebooking_diag", "Notes", None))
        self.label_3.setText(_translate("makebooking_diag", "Tech Assigned", None))
        self.label_49.setText(_translate("makebooking_diag", "Setup Location", None))
        self.label_7.setText(_translate("makebooking_diag", "Time Out", None))
        self.otb_timeOut.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_6.setText(_translate("makebooking_diag", "Time In", None))
        self.otb_timeIn.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_4.setText(_translate("makebooking_diag", "Date Out", None))
        self.otb_sameDay.setText(_translate("makebooking_diag", "Same Day Return", None))
        self.label_10.setText(_translate("makebooking_diag", "Date In", None))
        self.label.setText(_translate("makebooking_diag", "Ticket Number ", None))
        self.label_2.setText(_translate("makebooking_diag", "Client Name ", None))
        self.bookingTypeTab.setTabText(self.bookingTypeTab.indexOf(self.singleInstanceBooking), _translate("makebooking_diag", "One Time Booking", None))
        self.label_25.setText(_translate("makebooking_diag", "Ticket Number ", None))
        self.label_24.setText(_translate("makebooking_diag", "Client Name ", None))
        self.label_36.setText(_translate("makebooking_diag", "Tech Assigned", None))
        self.label_52.setText(_translate("makebooking_diag", "Setup Location", None))
        self.label_68.setText(_translate("makebooking_diag", "Equipment Needed", None))
        self.wb_equipment.setItemText(0, _translate("makebooking_diag", "Laptop", None))
        self.wb_equipment.setItemText(1, _translate("makebooking_diag", "Projector", None))
        self.wb_equipment.setItemText(2, _translate("makebooking_diag", "Screen", None))
        self.wb_equipment.setItemText(3, _translate("makebooking_diag", "Speaker", None))
        self.wb_equipment.setItemText(4, _translate("makebooking_diag", "Microphone(PC)", None))
        self.wb_equipment.setItemText(5, _translate("makebooking_diag", "VGA Cable ", None))
        self.wb_equipment.setItemText(6, _translate("makebooking_diag", "Extension/Surge", None))
        self.wb_equipment.setItemText(7, _translate("makebooking_diag", "DVD Player", None))
        self.wb_equipment.setItemText(8, _translate("makebooking_diag", "VCR", None))
        self.wb_equipment.setItemText(9, _translate("makebooking_diag", "21\' Monitor", None))
        self.wb_equipment.setItemText(10, _translate("makebooking_diag", "PA System", None))
        self.wb_equipment.setItemText(11, _translate("makebooking_diag", "Video Recording", None))
        self.wb_equipment.setItemText(12, _translate("makebooking_diag", "Doc Cam", None))
        self.wb_equipment.setItemText(13, _translate("makebooking_diag", "Microphone (AV)", None))
        self.wb_equipment.setItemText(14, _translate("makebooking_diag", "Plasma Screens", None))
        self.wb_equipment.setItemText(15, _translate("makebooking_diag", "New Item", None))
        self.label_69.setText(_translate("makebooking_diag", "Setup Type", None))
        self.wb_setup.setText(_translate("makebooking_diag", "Setup ", None))
        self.wb_pickup.setText(_translate("makebooking_diag", "Pickup", None))
        self.label_37.setText(_translate("makebooking_diag", "Start", None))
        self.label_38.setText(_translate("makebooking_diag", "End", None))
        self.wb_monday.setText(_translate("makebooking_diag", "Monday", None))
        self.label_39.setText(_translate("makebooking_diag", "From ", None))
        self.wb_timeOutMonday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_40.setText(_translate("makebooking_diag", "To", None))
        self.wb_timeInMonday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_42.setText(_translate("makebooking_diag", "To", None))
        self.wb_timeInTuesday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.wb_timeOutTuesday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_41.setText(_translate("makebooking_diag", "From ", None))
        self.wb_tuesday.setText(_translate("makebooking_diag", "Tuesday", None))
        self.wb_timeOutWednesday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_43.setText(_translate("makebooking_diag", "From ", None))
        self.label_44.setText(_translate("makebooking_diag", "To", None))
        self.wb_timeInWednesday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.wb_wednesday.setText(_translate("makebooking_diag", "Wednesday", None))
        self.wb_thursday.setText(_translate("makebooking_diag", "Thursday", None))
        self.label_45.setText(_translate("makebooking_diag", "From ", None))
        self.wb_timeOutThursday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_46.setText(_translate("makebooking_diag", "To", None))
        self.wb_timeInThursday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.wb_friday.setText(_translate("makebooking_diag", "Friday", None))
        self.label_47.setText(_translate("makebooking_diag", "From ", None))
        self.wb_timeOutFriday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_48.setText(_translate("makebooking_diag", "To", None))
        self.wb_timeInFriday.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_57.setText(_translate("makebooking_diag", "Notes", None))
        self.bookingTypeTab.setTabText(self.bookingTypeTab.indexOf(self.weeklyInstanceBookings), _translate("makebooking_diag", "Weekly Bookings ", None))
        self.label_63.setText(_translate("makebooking_diag", "Ticket Number ", None))
        self.label_62.setText(_translate("makebooking_diag", "Client Name ", None))
        self.label_65.setText(_translate("makebooking_diag", "Tech Assigned", None))
        self.label_51.setText(_translate("makebooking_diag", "Setup Location", None))
        self.label_105.setText(_translate("makebooking_diag", "Equipment Needed", None))
        self.mib_equipment.setItemText(0, _translate("makebooking_diag", "Laptop", None))
        self.mib_equipment.setItemText(1, _translate("makebooking_diag", "Projector", None))
        self.mib_equipment.setItemText(2, _translate("makebooking_diag", "Screen", None))
        self.mib_equipment.setItemText(3, _translate("makebooking_diag", "Speaker", None))
        self.mib_equipment.setItemText(4, _translate("makebooking_diag", "Microphone(PC)", None))
        self.mib_equipment.setItemText(5, _translate("makebooking_diag", "VGA Cable ", None))
        self.mib_equipment.setItemText(6, _translate("makebooking_diag", "Extension/Surge", None))
        self.mib_equipment.setItemText(7, _translate("makebooking_diag", "DVD Player", None))
        self.mib_equipment.setItemText(8, _translate("makebooking_diag", "VCR", None))
        self.mib_equipment.setItemText(9, _translate("makebooking_diag", "21\' Monitor", None))
        self.mib_equipment.setItemText(10, _translate("makebooking_diag", "PA System", None))
        self.mib_equipment.setItemText(11, _translate("makebooking_diag", "Video Recording", None))
        self.mib_equipment.setItemText(12, _translate("makebooking_diag", "Doc Cam", None))
        self.mib_equipment.setItemText(13, _translate("makebooking_diag", "Microphone (AV)", None))
        self.mib_equipment.setItemText(14, _translate("makebooking_diag", "Plasma Screens", None))
        self.mib_equipment.setItemText(15, _translate("makebooking_diag", "New Item", None))
        self.label_102.setText(_translate("makebooking_diag", "Time Out", None))
        self.mib_timeOut.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_101.setText(_translate("makebooking_diag", "Time In", None))
        self.mib_timeIn.setDisplayFormat(_translate("makebooking_diag", "h:mm AP", None))
        self.label_66.setText(_translate("makebooking_diag", "From ", None))
        self.label_67.setText(_translate("makebooking_diag", "To", None))
        self.label_64.setText(_translate("makebooking_diag", "Setup Type", None))
        self.mib_setup.setText(_translate("makebooking_diag", "Setup ", None))
        self.mib_pickup.setText(_translate("makebooking_diag", "Pickup", None))
        self.mib_councilRoomSetup.setText(_translate("makebooking_diag", "Council Room (Setup)", None))
        self.mib_councilRoomStay.setText(_translate("makebooking_diag", " Council Room (Stay)", None))
        self.mib_addNewDate.setText(_translate("makebooking_diag", "Add", None))
        self.mib_removeNewDate.setText(_translate("makebooking_diag", "Remove", None))
        self.label_56.setText(_translate("makebooking_diag", "Notes", None))
        self.bookingTypeTab.setTabText(self.bookingTypeTab.indexOf(self.multipleInstanceBookings), _translate("makebooking_diag", "Multiple Instance Bookings", None))

